query fetchEmployees($first: Int, $skip: Int) {
    allEmployees: allEmployees(first: $first, skip: $skip) {
        id
        name
        engName
        position {
            name
            engName
        }
        snapshotUrl {
            urlOriginal
        }
    }
}
query fetchEmployee($id: ID!) {
    employee: Employee(where: { id: $id }) {
        id
        name
        engName
        position {
            name
            engName
        }
        snapshotUrl {
            urlOriginal
        }
        headerUrl {
            urlOriginal
        }
    }
}
