query fetchImages($first: Int, $skip: Int) {
    allImages: allImages(first: $first, skip: $skip) {
        id
        name
    }
}

mutation updateImages($data: [ImagesUpdateInput]) {
    updateImages(data: $data) {
        id
        keywords
    }
}

query fetchPortfolios($first: Int, $skip: Int) {
    allPortfolios: allPortfolios(
        first: $first
        skip: $skip
        orderBy: "date_DESC"
    ) {
        id
        name
        date
        coverPhoto {
            urlOriginal
        }
        photos {
            urlOriginal
        }
    }
}
query fetchPortfolio($id: ID!) {
    portfolio: Portfolio(where: { id: $id }) {
        id
        name
        coverPhoto {
            urlOriginal
        }
        photos {
            urlOriginal
        }
        descriptionApiData
    }
}
