query fetchAllPositions {
    allPositions {
        name
        engName
        employee {
            id
            name
            engName
            position {
                name
                engName
            }
            snapshotUrl {
                urlOriginal
            }
        }
    }
}
