query fetchAllPositions {
    allPositions(orderBy: "order_desc") {
        name
        engName
        order
        employee {
            id
            name
            engName
            position {
                name
                engName
            }
            snapshotUrl {
                urlOriginal
            }
            headerUrl {
                urlOriginal
            }
        }
    }
}
